<?php $this->load->view('include/web_head.php'); ?>

<body class="mysub_lag translate_v  " style="font-family:arial;">
 <!-- <div class="laga">
        <div id="google_translate_element"></div>
    </div>-->
<?php $this->load->view('include/main_header.php'); ?>


<br>
<br>
<div class="fullcontainer	terms_conditions">

<p> <strong>Terms of use</strong></p>
<p> <strong>YOUR USE OF THE SERVICES OF THIS WEB SITE CONSTITUTES YOUR AGREEMENT TO BE BOUND BY THESE TERMS OF USE.</strong></p>
<p> This Web site (the "Web Site") is for the services made available by bestadvicer ("Provider") and all content, information and software made available through the Web Site ("Content") may be used solely under the following terms ("Terms of Use").</p>

<p> <strong>USER(S) ELIGIBILITY </strong></p>

<p>By accepting these terms and conditions, you warrant that you have completed 18 years of age as on date of this agreement and that you have fully read and understood the Terms and Conditions as set forth in this agreement, without any impairment in judgment resulting from (but not limited to) mental illness, mental handicap, intoxication, medication, or any other health or other problem that could impair judgment. </p>
<p>You acknowledge that SUCCESSTAINMENT PVT. LTD. is the owner/proprietor of the domain name and website, bestadvicer.com (https://www.bestadvicer.com) (from now on referred to as, “the website” or “bestadvicer” or “the site”). </p>

<p> <strong>LIMITATION OF LIABILITY</strong></p>
<p>You also absolve professionals engaged by <a href="https://bestadvicer.com/"> www.bestadvicer.com</a>who offers services through the website from any responsibility or liability whatsoever, for any medical, legal or financial events or outcomes related to services attained by you through the use of second opinion (also referred at bestadvicer as “online consultation” or “online consult” or “consultations” or “consults” or “queries” or “video queries” or “direct query to a consultant” or “follow-up query” or “free query” or “paid query” or “common query” or “consultation” or “appointment”). You also understand and use the website accepting that it is being provided on an as is basis. </p>

<p> <strong>PURPOSE OF BEST ADVICER</strong></p>
<p>bestadvicer provides you with a forum to interact with consultants and professionals who have registered on the website. You understand and agree that information provided on bestadvicer is for information purpose only, and does not constitute advice given by a particular authorised professional. Professional advice by authorised professionals is the application and interpretation of concerned particular subject/field/profession to an individual’s specific circumstances, and is expressly prohibited on bestadvicer. </p>
<p>You understand and agree that you will not rely on the information presented on bestadvicer for your specific situation, and that you will seek concerned authorised professional’s for your own situation. </p>
<p> <strong>DISSEMINATION OF INFORMATION</strong></p>
<p>bestadvicer collects, directly or indirectly, and displays on the Website, relevant information regarding the profile of the Consultants and their field of expertise listed on the Website, such as their qualification, fees, and other necessary details. bestadvicer takes reasonable efforts to ensure that such information is updated routinely. bestadvicer cannot be held liable for any inaccuracies or incompleteness reflected by the information or pictures shared on the website as bestadvicer takes reasonable efforts to vet the information before uploading to the website.</p>
<p> <strong>REFERRAL/ENDORSEMENT</strong></p>
<p>You understand that bestadvicer may not verify licences of professionals who have registered on bestadvicer to provide information and consultation to users, and that it is your sole responsibility to verify a professional’s licence and credentials before making a decision to hire such a professional. You understand that bestadvicer is not an advertising service for professional and consultants, and that the professionals and consultants listing on bestadvicer do not constitute a referral or endorsement by bestadvicer. </p>
<p> <strong>SUBSCRIPTION</strong></p>
<p>You understand and agree that bestadvicer may include certain communications from bestadvicer, such as service announcements, administrative messages, newsletters, and that these communications are considered part of bestadvicer membership and you will not be able to opt out of receiving them. Unless explicitly stated otherwise, any new features that augment or enhance the current bestadvicer services, including the release of new bestadvicer properties, shall be subject to the user agreement.</p>
<p> <strong>FEES TO THE THIRD PARTY</strong></p>
<p>You understand and agree that bestadvicer is provided “AS IS” and that bestadvicer assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings. You are responsible for obtaining access to bestadvicer, and that access may involve third-party fees (such as internet service provider or airtime charges). You are responsible for those fees. In addition, you must provide and are responsible for all equipment necessary to access bestadvicer. </p>

<p> <strong>TRANSMISSION THROUGH NETWORK OR DEVICES</strong></p>
<p>You understand that the technical processing and transmission of bestadvicer, including your content, may involve. (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. </p>
<p>We use our reasonable endeavours to ensure the accuracy of the information provided on the bestadvicer.com service. </p>

<p> <strong>DOWNLOADING OR ACCESSING</strong></p>
<p>By downloading or accessing the Website to use the Services; you irrevocably accept all the conditions stipulated in this Agreement and agree to abide by them. This Agreement supersedes all previous oral and written terms and conditions (if any) communicated to you relating to your use of the Website to avail the Services. By availing any Service, you signify assent to the terms of this Agreement.</p>
<p>The User(s) is solely responsible for any damage to its computer system or loss of data that may result from the download of any material or otherwise obtained through the Web site.</p>
<p> <strong>ACCURACY OF INFORMATION</strong></p>
<p>We do not warrant or guarantee the accuracy, reliability or legality of any of the information contained in the <a href="https://bestadvicer.com/"> www.bestadvicer.com</a> we make no warranty that the contents of this site are free from infection by viruses or anything else which has contaminating or destructive properties. Reserves the right, at its discretion, from time to time to make changes to the information provided on the<a href="https://bestadvicer.com/"> www.bestadvicer.com</a>  service, or to alter the nature of the www.bestadvicer.com  service. Will not guarantee the availability of the <a href="https://bestadvicer.com/"> www.bestadvicer.com</a> service during maintenance of the website. </p>

<p> <strong>CONTENT AVAILABLE ON THE WEBSITE</strong></p>
<p>bestadvicer will not be responsible for the site content provided by advertisers including product/service performance claims, advertisement and/or sales promotions is the sole responsibility of such advertisers and they alone shall be liable for all disputes and liabilities arising therefrom and bestadvicer will in no way be responsible for it. </p>

<p> <strong>DAMAGES </strong></p>
<p><a href="https://bestadvicer.com/"> www.bestadvicer.com</a> and its affiliates, associates, agents or employees shall not be liable, at any time for any damages (including, damages for loss of profits or loss of business) arising in contract, or otherwise from the use of or inability to use the site, or any of its contents, or from any act(s) or omission(s) a result of using the site or any such contents or of any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communications line failure, theft or destruction or unauthorised access to, alteration of, or use of information contained on the site. </p>
<p> <strong> ERRORS OR OMISSIONS </strong></p>
<p>bestadvicer has compiled data from a variety of sources on this website and reserves the right, in its sole discretion, to correct any errors or omissions in any portion of the site. www.bestadvicer.com may make any other changes to the site, the materials and the products, programs, services or prices (if any) described in the site at any time without notice. </p>
<p>You are therefore advised to check the information provided to you through the<a href="https://bestadvicer.com/"> www.bestadvicer.com</a>service as any reliance that you place on the accuracy of that information is at your own risk. </p>
<p> <strong>PROMOTIONS OFFERED</strong></p>
<p>While users are offered free access to<a href="https://bestadvicer.com/"> www.bestadvicer.com</a>service, <a href="https://bestadvicer.com/"> www.bestadvicer.com</a>reserves the right to discontinue these free promotions at any time and with no notice given. </p>
<p> <strong>TARGET AUDIENCE</strong></p>
<p> <strong>Our target audience are also include(but not limited to):-</strong></p>
<p>Worried and anxious people who are looking for quick medical clarification. </p>
<p>People who seek a second opinion based on existing reports and detailed history of their problem/issue.</p>
<p>Expats & travellers who are looking for a quick connect with consultants/professional’s without disrupting their schedule. </p>
<p> <strong>The website is not intended to be used to:</strong></p>
<p>1.	Treat a medical emergency or medical condition.</p>
<p>2.	Advice or resolve legal, medical or financial issues outside the scope of what has been agreed or provided. </p>

<p> <strong>For any medical emergency, You shall immediately contact the emergency number in your country.</strong></p>
<p>Information or advice provided on the site by professionals should be used merely as a guide rather than a definitive recommendation to adopt any specific action or treatment. Nothing transmitted to or from this site constitutes the establishment of a doctor-patient or lawyer-client relationship between you and any professional or person providing information or advice through the site. The site is not intended to diagnose a medical condition. </p>
<p> <strong>VIEWS EXPRESSED ON THE WEBSITE</strong></p>
<p>You understand and agree that bestadvicer does not regularly review the posts on the site (excluding, however, bestadvicer right to access accounts to ensure that the system is working and/or in the case of any technical dysfunction) and the views expressed therein those of the posters or any content or any answer do not necessarily reflect those of bestadvicer, its own managers, directors, doctors, lawyers, Career Advicers, Spiritual Advicers, Personal Counsellors, Business Advicers, Techies, Lifestyle Advicers, moderator, employees, agents, partners, advertisers or affiliates. </p>
<p> <strong>RESPONSIBILITY</strong></p>
<p>bestadvicer assumes no responsibility for the posts or the information contained therein, nor does it make any claims, promises or guarantees about the accuracy, suitability or completeness of any of the information on the site or in the post. All consultations or information obtained directly or indirectly for the site are provided at your own risk. </p>
<p>For all consultations including medical consultations in particular, before acting on any of the consultation offered in/through the site, you should confirm that such action is applicable and suitable to you, by referring to you own medical practitioner or other authorised professional’s or consultants or by obtaining a second and third opinion of other medical practitioners or other authorised professional’s or consultants. The limitations associated with consultations or other services exclusive of physical examination, in-person legal advice or onsite and extensive investigations are hereby accepted and agreed to by you. </p>
<p> <strong>For all consultations including medical consultations in particular, before acting on any of the consultation offered in/through the site, you should confirm that such action is applicable and suitable to you, by referring to you own medical practitioner or other authorised professional’s or consultants or by obtaining a second and third opinion of other medical practitioners or other authorised professional’s or consultants. The limitations associated with consultations or other services exclusive of physical examination, in-person legal advice or onsite and extensive investigations are hereby accepted and agreed to by you. </strong></p>
<p> <strong>You further absolve from all liability, bestadvicer and its owners, managers, directors, doctors, lawyers, career counsellors, Astrologers, Personal Counsellors, Business Advicers, Tech Consultants, Investment Advicers, Spiritual Advicers, Lifestyle Advicers, moderator, employees, agents, partners, advertisers or affiliates from any legal responsibility for any incorrect or misleading information provided by any person professional or contained within site. </strong></p>
<p>bestadvicer may, without giving notice, delete any account or information contained on the site for any reason whatsoever. </p>
<p> <strong>GENERAL INFORMATION PURPOSE NOT A SUBSTITUTE FOR SOUND PROFESSIONAL ADVICE</strong></p>
<p>The information on this Website (including but not limited to video consult, live chat, emails, phone support) is provided for general informational purposes only and SHOULD NOT be relied upon as a substitute for sound professional advice or any authorised professional’s advice, evaluation or care from your authorised professional’s/consultants or other qualified/approved/authorised consultants/treatment providers. </p>
<p>The information furnished on this Website and the interactive responses (if any) furnished by or through, this Website are not intended to or implied to be professional advice. You shall consult other sources and confirm the information contained within this Website. This shall include consulting your own authorised/approved/qualified consultants/treatment providers/professional’s regarding the applicability of any opinions or recommendations with respect to your symptoms or facts or conditions of case/issue. </p>

<p> <strong>MEDICAL CONCERNS</strong></p>
<p>For medical concerns, including decision about medications and other treatments, you shall always consult your physician or other, qualified healthcare professional. In serious cases, You shall seek immediate assistance from emergency personnel. If you suspect that you have a medical problem or condition, you shall contact a physician or other qualified healthcare provider(s) immediately.<strong>YOU SHALL NEVER DISREGARD MEDICAL ADVICE OR DELAY IN SEEKING IT BECAUSE OF SOMETHING YOU HAVE READ ON THIS WEBSITE</strong>WEBSITE (including but not limited to video consult, live chat, emails, phone consult). No medications, diet supplements or treatments or any sort/category of consultation as may be described on this Website shall be taken or begun without first consulting your physician or other healthcare providers or authorised professional’s.</p>
<p> <strong>RISK</strong></p>
<p>You understand/agree that bestadvicer makes no claim that the contents of the site, such as text, graphics, images and information obtained from service providers and any other material contained on the Site (the “Content”) is appropriate or may be downloaded in a particular jurisdiction. Access to the Site and Content may not be legal by certain persons or in certain states or countries. If you access the Site from outside India, You do so at your own risk and are responsible for compliance with the laws of your jurisdiction. Provisions relating to the liability of bestadvicer and its licensors, user submissions, Indemnity, Jurisdiction, and Complete Agreement, survive the expiration or termination of these Terms and Use for any reason whatsoever. </p>
<p> All content (including health content on site and articles) on the platform is for informational purposes only. </p>
<p>The content is not intended to be a substitute for face-to-face professional advice, consultation, diagnosis, or treatment. You shall always seek the advice of a physician within your jurisdiction with any questions regarding a medical condition. You will never disregard professional medical advice or authorised professional consultation or delay in seeking it because of information provided by a medical professional or any other authorised professional or consultant through the site.  If you think you may have a medical emergency, you shall call your doctor or emergency services immediately. </p>
<p>bestadvicer does not recommend or endorse any specific tests, products, procedures, opinions, or other information that may be mentioned on the Site. Reliance on any information provided by any professional through the Site, bestadvicer employees, other appearing on the Site at the invitation of bestadvicer, or other visitors to the Site is solely at your own risk. </p>
<p> <strong>POST OR ATTEMPT TO POST</strong></p>
<p>You agree that you will not use the Site to post any advertisement or other commercial messages. You further agree that you will not post or attempt to post any content whatsoever on the website of bestadvicer, which to your knowledge is knowingly false, defamatory, inaccurate, abusive, harassing, obscene, sexually oriented or threatening message or material irrespective of whether the same is defamatory or illegally invasion of another person’s privacy. </p>
<p>If any complaint is received against you to this effect, then upon receiving such complaint bestadvicer can choose to delete any inappropriate posts as quickly as possible; however, the submissions are generally posted in real-time and are not reviewed by bestadvicer before they are published to the Site. You also agree that your queries/consultations can be released for public view (after bestadvicer removes all the private details and publishes it anonymously). </p>
<p> <strong>PRIVACY </strong></p>
<p>You agree and affirm that you shall not ask or request for the contact information of any Professional/consultant on bestadvicer by using up your services and cannot hold bestadvicer responsible for any sorts of communication that takes between you and the Professionals/Consultants on the site. </p>
<p> <strong>Copyright</strong></p>
<p>You agree and affirm that the Content (excluding all correspondence between you and any person or professional through the messaging system, including any and all attachments) (“Copyright Content”) is protected by Copyright under Central and State Laws of the republic of India, and foreign laws as applicable. Title to the Copyright Content remains with Bestadvicer or its Licensors. Any use of the Copyright Content not expressly permitted by these Terms and Conditions is a breach of the Terms and Conditions and may violate copyright, trademark, and other laws. Inquiries or applications for permission to Copy and Copyright Content otherwise than is permitted by these Terms and Conditions should be directed to info@bestadvicer.com. Contents and features on the Site, including these Terms and Conditions are subject to change or termination without notice in the editorial discretion of bestadvicer. All rights not expressly granted herein are reserved to bestadvicer and its licensors. If you violate any of these Terms and Conditions, then your right for Copyright Content is automatically terminated and You must immediately destroy and copy that You have of any portion of the Copyright Content, lest You shall be liable for infringement of Copyright. </p>
<p>You agree that you shall use the Site on your own free will and shall not be guided in any manner including by way of any promotional emails, phone calls and advertisements from bestadvicer and its affiliates and partners. The use of the Site and the Content is therefore entirely at you own risk. When using the Site, information will be transmitted over a medium which, may in cases, is beyond the control and jurisdiction of bestadvicer and its suppliers. Accordingly, bestadvicer assumes no responsibility or liability whatsoever for or relating to the delay or failure of delivery of data, interruption or corruption of any data or other information transmitted in connection with use of the Site. </p>
<p> <strong>WARRANTIES</strong></p>
<p>The site and the content are provided on an “as is” basis. bestadvicer, its licensors, and its suppliers, to the fullest extent permitted by law, disclaim all warranties, either express or implied, statutory or otherwise, including but not limited to the implied warranties of merchantability, non-infringement of third parties rights, and fitness for particular purpose. Specifically, bestadvicer, its Licensors, and its suppliers make no representations, warranties or guarantees about the following:</p>
<p>1.	The accuracy, reliability, completeness, correctness, authenticity or timeliness of the Content, software, text, graphics, links, or communications provided to you through the use of the site. </p>
<p>2.	The compliance by bestadvicer, with government laws, rules, regulations and notifications in force in any country, or the laws of any jurisdiction with regard to the ability to use the Site or requiring disclosure of information contained on the Site. </p>
<p> <strong>DAMAGES or CLAIMS</strong></p>
<p>You agree that, to the fullest extent permitted by law, neither bestadvicer, its Licensors, its suppliers, nor any third parties mentioned on the Site shall, in any event whatsoever, be liable for any damages or legal disputes (including, without limitation, incidental and consequential damages, arbitration, personal injury/wrongful death, litigation, lost profits, or damages resulting from lost data or business interruption, including and computer virus, claim for disability benefits, claim for worker’s compensation and/or malpractice claims without the prior written consent of bestadvicer) resulting from the use or inability to use, by the user, of the Site or the Content, Whether based on warranty, contract, tort, or any other Legal theory, and whether or not bestadvicer is advised of the possibility of such damages. </p>
<p> <strong>CLAIMS</strong></p>
<p>To the extent permitted by law, all legal claims if any, arising in connection with your use of the site and any of its Content, shall be brought within thirty (30) days from the date of occurrence of the event giving rise to such action. </p>
<p>bestadvicer does not endorse any professional and does not intend to be a source of advertising, solicitation or legal advice on the behalf of any professional. To the fullest extent permitted by law, bestadvicer is not responsible for the content of linked third-party sites, sites framed within the Site, or third-party advertisements, and does not make any representations regarding their legality, content or accuracy. You at your own risk is subject to the terms and conditions of use for such sites of the respective sites. bestadvicer does not endorse any product advertised on the Site. </p>
<p>All information available on this Website is not exhaustive and is provided “AS IS” and without any warranties of any kind, either express or implied. All implied warranties of merchantability and fitness for a particular purpose or use are hereby excluded. Disclaimer of Liability of the Medical Centre, if any, for damages (including without limitation liability arising out of tort, strict liability, negligence, contract or patent or copyright infringement) shall not exceed the lesser of (i) the fees paid, if any, to bestadvicer for the particular information or service provided on this Website or (ii) Rs. 100 (Indian National Rupees) or the equivalent currency. </p>
<p> <strong>INDEMNITY</strong></p>
<p>bestadvicer shall not be liable under any theory of indemnity. In no event shall bestadvicer be liable for any damages other than the amount referred to above. All other damages, direct or indirect, special, incidental, consequential or punitive are hereby waived by the user to the fullest extent permitted by law, even if <a href="https://bestadvicer.com/"> www.bestadvicer.com</a> (https://www.bestadvicer.com) had been advised of the possibility of such damages. bestadvicer expressly disclaims and DOES NOT WARRANT that the functioning of this Website will be uninterrupted or error free or that they are correct; that any errors will be corrected; that any information on this Website is complete, accurate (although the Medical Centre strives for accuracy), or timely (or will be updated); and that this Website, or the server that makes it available, is or will be free of viruses or other harmful components. You are solely responsible for any damages to your computer system or mobile phone or tablet or loss of data that results from downloading any material from this Website. </p>
<p>YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT <a href="https://bestadvicer.com/"> www.bestadvicer.com</a> ,ITS LICENSORS, SUPPLIERS AND BUSINESS PARTNERS ARE NOT RESPONSIBLE IN ANY WAY AND IN ANY MANNER WHATSOEVER FOR THE RESULTS OF YOUR DECISIONS RESULTING FROM THE USE OF THIS WEBSITE OR THE INFORMATION CONTAINED HEREIN, INCLUDING BUT NOT LIMITED TO, YOU CHOOSING TO SEEK OR NOT TO SEEK PROFESSIONAL MEDICAL CARE, OR ANY OTHER KIND OF PROFESSIONAL CONSULTATION, OR CONSULTATION’S OR CHOOSING OR NOT CHOOSING SPECIFIC TREATMENT BASED ON THE INFORMATION ON OR ACCESSED THROUGH THIS WEBSITE (Including but not limited to video consult, Live chat, Email, Phone).</p>
<p>You agree that you are solely responsible for anything posted on the Site, you further agree to defend, indemnify, compensate and hold bestadvicer, its officers, directors, employees, doctors, lawyers, consultants, advisors, moderators, agents, licensors, and suppliers, harmless from and against all claims, actions or demands, liabilities and settlements including without limitation, reasonable legal and accounting fees, resulting from, or alleged to result from your any act/omission violating these Terms and Conditions or any claims based upon your posts/submissions on the Site. </p>
<p> <strong>SPAM POLICIES</strong></p>
<p>You consent to abide by the spam policies and undertake not to forward unsolicited mails using the “Refer a Friend” feature from bestadvicer server to any of your contacts without their prior consent. Failure to do so may result in cancellation of their account with bestadvicer. </p>
<p> <strong>ENDORSEMENT OR RECOMMENDATIONS</strong></p>
<p>You also agree and state that you have understand the professionals that participate in the Site may or may not be affiliated with, employed by or agents of bestadvicer and that bestadvicer makes no representations as to the qualifications of any of the professional’s/consultants who participate in the network. Any listing, name, content, material of any professional or firm found on this site does not constitute any endorsement or recommendations. When deciding to take advice and/or hire any professional or firm, you shall conduct a prior independent research as to the accuracy of the credentials expressed in the content. </p>
<p> <strong>COMMUNICATION</strong></p>
<p>You authorize bestadvicer to contact you via email and phone call to provide information and notification pertaining to services provided on the site. You also agree for bestadvicer to send transactional SMS to the mobile number which you have registered on the site (with the option to opt-out (/users/opt out sms) if necessary). </p>
<p> <strong>PRICING STRUCTURE</strong></p>
<p>You agree to pay an annual membership fee if applicable and the necessary consultation fee, pursuant to the schedule of memberships and fee set forth on the bestadvicer. Bestadvicer reserves the right to modify its pricing structure at any time and implement the new price structure at any time prior to billing the client for his or her initial payment or for future payments that are due pursuant to this agreement. </p>
<p> <strong>CANCELLATIONS</strong></p>
<p>You understand and agree that all consultations cancelled with less than 4 hours notice will be charged the full consultation amount, said amount to be set forth on  the bestadvicer.</p>
<p> <strong>Payment Policy:</strong></p>
<p>Services against any Plan order will be available once you have made payment for services according to the requirement of the corresponding Plan Order. Bestadvicer has no obligation render services under any Plan if the payments as required under any Plan Order have not been made.</p>
<p>When you purchased the Service, you agreed to a specific price and plan, where such Plan may be for a different duration (Term Plan). Plans can also have Bestadvicer License. </p>
<p> <strong>PLANS</strong></p>
<p>You understand that certain Plans may have fee including but not limited to Service Fee and/or Activation Fee and/or Bestadvicer License Fee payable either on an annual Payment Plan or on a Monthly basis, Recurring Payment plan. Subject to the applicable Term Plan, all payments under the Annual Plan shall be made upfront at time of Subscription cycle. For payments under the Recurring Payment Plan, all payments fees shall be made in advance apart from the monthly instalments of the Service Fee, payable payment term. You shall be charged an additional non-refundable Activation Fee at the time of registration as specified in the Plan Order. The fee (including Activation Fee/bestadvicer License Fee) be refunded as per the provisions of Refund specified herein. All fee under this clause or a relevant Plan Order, is payable at the time of Commencement of the Plan. </p>
<p> <strong>LICENSE FEE</strong></p>
<p>Bestadvicer License Fee will be paid alongwith the Service Fee and shall remain valid for period of 5 years from the date of subscription. While opting for an Upgrade of your Plan as per the terms of the Upgrade offer, All terms of Service Fee and/or any other fee payable under any mode of payment for a subscription shall be set forth in the applicable Plan. Plans may offer a discount on the Service if you sign up for other bestadvicer services (Bundle Discount). You agree to maintain your service and the bundled services for the applied up for a Term Plan or a Bundle Discount, the Price available with those Plans is valid until one of the following occurs: (1) the term Plan expires; (2) you drop on of the bestadvicer service purchase to receive the special rate as notified to bestadvicer; or (3) You terminate the agreement/Plan before the expiry of the relevant term. </p>
<p> <strong>FOLLOW-UP FEE</strong></p>
<p>You understands that the content permissible to be typed in any query (direct to a doctor, consultant or any other professional consultant available on the bestadvicer.com, follow-up query or posting it as a paid query on common query system) should be less than 500 words and/or files attached in the query should be less than or equal to 5. The same rules apply for phone or video consultations (direct consultation to a doctor, any other consultant, professional consultant/follow-up consultation to a consultant or professional/common consultation booking). Content typed more than 500 words and/or attachments more than 5 will be taken as another query/consultation and additional fee (the fee will be as same as the parent query/consultation) till it reaches another 500 words and 5 more attachments. You understand that this rule works in arithmetic progressions. Example : A query or content having 1500 words and 5 attachments (or) even 500 words with 15 attachments will be taken as 3 queries/consultation and thrice the fee of the parent query/consultation can be automatically deducted from your credit card or wallet balance or balance from bestadvicer wallet of a client will automatically be deducted. 
The calendar as seen on the bestadvicer is based on Indian Standard Times (I.S.T.). if you are outside of the IST time zone, it is my responsibility, at the time of scheduling and at the time of attendance of their consultation, to accommodate for this difference
.</p>
<p> <strong>Refund Policy:</strong></p>
<p>Bestadvicer will not, under any circumstances, issue cash refunds or credits for early contract cancellation or refund payment for any consultation, once charged. If you have a question about charges made to my account, You shall contact customercare@bestadvicer.com (mailto:customercare@bestadvicer.com) immediately. Even if the charges were made in error, bestadvicer still has the sole discretion to credit the account or credit card account for the appropriate or corresponding amount. Bestadvicer has a zero-tolerance policy for chargebacks. Your any dispute of a credit card payment that is found to be valid is subject to a fine, suspension and account termination subject to bestadvicer discretion. Any chargeback fees, past due fees and costs will be sent to collections. </p>
<p>If bestadvicer collection efforts fail, unpaid debts will be reported to all available credit reporting agencies. Booking and cancelling an consultation within 24 hours at any particular point of time will not allow refund of the Consultation fee. </p>
<p>Bestadvicer shall issue a full refund after the moderation team does an internal enquiry (after my complaint) to check the quality. However the decision to refund vests with bestadvicer.</p>
<p> <strong>ARBITRATION AND CLASS ACTION WAIVER</strong></p>
<p> <strong>Arbitration</strong></p>
<p>Any claim, dispute, or controversy (Claim) arising out of or relating to this Terms of use and Agreement or the relationships among the parties hereto shall be resolved by arbitration through binding arbitration administered and adjudicate according to the provisions of The Arbitration and Conciliation Act, 1996(As Amended up to date), in effect at the time the Claim is filed. The arbitrator’s decision shall be final, binding, and non-appealable. </p>
<p> <strong>AWARDS</strong></p>
<p>Judgment upon the award may be entered and enforced in any court having jurisdiction or application may be made for judicial acceptance of the award and an order of enforcement. The arbitrator, and not any federal, state, or local court, shall have exclusive authority to resolve any dispute relating to the interpretation, applicability, enforceability, or formation of this Agreement including any claim that all or any part of the Agreement is void or voidable. The arbitration proceedings shall be held in Mathura, Uttar Pradesh/Agra, Uttar Pradesh/Delhi India and shall be subject to the terms of this Agreement, the intentions of the parties as stated herein, international commercial practice, and the governing law of this Agreement. No arbitration or proceeding will be combined with another without the prior written consent of all parties to all affected arbitrations or proceedings.</p>
<p> <strong>Class Action Waiver</strong></p>
<p>The Parties hereby expressly agreed that any Claim must be brought in the respective party’s individual capacity, and not as a plaintiff or class member in any purported class, collective, representative, multiple plaintiff, or similar proceeding (Class Action). The parties expressly waive any ability to maintain any Class Action in any forum. The arbitrator shall not have authority to combine or aggregate similar claims or conduct any Class Action nor make an award to any person or entity not a party to the arbitration. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator. THE PARTIES UNDERSTAND THAT THEY WOULD HAVE HAD A RIGHT TO LITIGATE THROUGH A COURT, TO HAVE A JUDGE OR JURY DECIDE THEIR CASE AND TO BE PARTY TO A CLASS OR REPRESENTATIVE ACTION. HOWEVER, THEY UNDERSTAND AND CHOOSE TO HAVE ANY CLAIMS DECIDED INDIVIDUALLY, THROUGH ARBITRATION. THE LAWS OF THE INDIA SHALL GOVERN THIS AGREEMENT.</p>
<p> <strong>DISPUTES</strong></p>
<p>Before you take a dispute to arbitration or to small claims court, you must first contact us by writing us and describing (a) the nature and basis of the Claim or dispute; and (b) the specific relief sought (Demand) and give us an opportunity to resolve the dispute. Similarly, before bestadvicer takes a dispute to arbitration, we must first attempt to resolve it by contacting you. If you and bestadvicer do not reach an agreement to resolve the claim within 60 days from the date you or bestadvicer is notified by the other of a dispute, you or bestadvicer may commence an arbitration proceeding. If your Claim is for Rupees 1,00,000 (Indian Rupees) or less, we agree that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, by telephone, or by an in-person hearing as established by the rules of the arbitration administrator.</p>
<p> <strong>ARBITRATION FEES</strong></p>
<p>The amount of any settlement offer made by bestadvicer shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you are entitled. If Bestadvicer prevails before the arbitrator, and if we show that you acted in bad faith in bringing your claim, then Bestadvicer may seek to recover the Arbitration fees and expenses of the arbitration from you.</p>
<p> <strong>Jurisdiction: </strong></p>
<p>You expressly agree that the exclusive jurisdiction for any dispute with bestadvicer, or in any way relating to use of the Site, resides in the courts of Mathura, Uttar Pradesh, India or Delhi, India. You further agree and expressly consent to the exercise of personal jurisdiction in the courts of Mathura, Uttar Pradesh, India or Delhi, India in Connection with any such dispute including any claim involving bestadvicer or its affiliates, subsidiaries, employees, contractors, officers, directors, telecommunication providers, and content providers. </p>
<p>You understand that these terms and conditions are governed by the internal substantive Indian laws of the land, without respect to its conflict of laws principles. If any provision of these Terms and Conditions is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms and Conditions, which shall remain in full force and effect. No waiver of any of these Terms and Conditions at any one point of time shall be deemed as a further or continuing waiver of such terms or condition or any other terms or condition a subsequent occasion. </p>
<p> <strong>LEGAL RELATIONSHIP</strong></p>
<p>These Terms and Conditions constitute the entire agreement between the parties and supersede all other agreements relating to this subject matter, and set out the complete legal relationship between bestadvicer and you arising from or connected with this subject matter. For the voidance of doubt, in the case of any conflict between these Terms and Conditions, and any other agreement, these Terms and Conditions will prevail over all or any of them. </p>
<p> <strong>RIGHT TO PLACE ANY THIRD PARTY ADVERTISEMENTS</strong></p>
<p>Bestadvicer reserves the right to place any third party advertisements on the Site at any time and without your notice or consent and without attracting any liability in this regard. Bestadvicer reserves the right to charge you in the future with prior notice. Bestadvicer reserve the right to release professionals responses in circumstances you have paid (or a professional has waived) the requisite fee owing to technical difficulties. If and when necessary, bestadvicer reserves the right to limit account holders use of bestadvicer Accounts. Questions or comments regarding the Site should be directed by electronic mail to </p>
<p><a	href="#">bestadvicer@bestadvicer.comI(mailto:bestadvicer@bestadvicer.com).</a></p>
<p> <strong>VERIFYING THE CREDENTIALS</strong></p>
<p>The contents on the portal are provided by bestadvicer for use by the online users as a quick reference of information about professionals, consultants, counsellors, lawyers, doctors, hospitals and other healthcare services providers. The listing of the professionals, consultants, counsellors, lawyers, doctors and other healthcare services providers on the portal is not intended as a tool for verifying the credentials, qualifications, or abilities of any person or organization. Inclusion in the Directory Listing does not imply recommendation or endorsement nor does omission in the Directory Listing imply bestadvicer disapproval. The professionals, consultants, counsellors, lawyers, doctors in bestadvicer panel are board certified practitioners (Registered Medical Practitioners) in their respective countries. </p>
<p> <strong>loss</strong></p>
<p>Any information provided by bestadvicer including the consultants, professionals, counsellors, doctors and lawyers on helpline (video consulting, Phone, Live Chat and Email) provided to me to make a more informed decision. Bestadvicer will not be responsible or liable in any manner whatsoever for any damages or any loss (including that of health, life, limb or livelihood) of any kind because of following the advice or instruction given by bestadvicer employees, owners, directors, doctors, lawyers, professionals, consultants, counsellors, moderators, associates, contractors, and online users. </p>
<p> <strong>PUBLICATION</strong></p>
<p>You understand that you are prohibited from republishing, selling, duplicating, or “scraping” for commercial or any other purpose whatsoever, the Directory Listing or any of the data or other information contained in the site, in whole or in part, in any medium whatsoever, and all such information and content posted on the site either by bestadvicer or any user or any one else authorized by bestadvicer to this extension, shall form exclusive property of bestadvicer. </p>
<p>You also agree to always seek the advice of a physician or other qualified health provider with any question you may have regarding a medical condition. You further agree never to disregard professional medical advice or delay in seeking it because of something that has been read on bestadvicer website or have had live video consulting or online chat or phone call or Email communication with an bestadvicer team member including the bestadvicer doctors.</p>
<p> <strong>LOSS OF DATA</strong></p>
<p>You understand and agree that bestadvicer shall under no circumstance be responsible for any lost or corrupted software or data. Bestadvicer strongly recommend complete data backup and disaster recovery plan. We will use commercially reasonable efforts to provide the support to you. Our experience shows that most issues/problems can be corrected/resolved by technicians/tech. consultants. Please listen carefully to the tech. consultant and follow his/her instructions. you must have knowledge regarding the hardware system, any software involved and in the facts and circumstances surrounding the incident. </p>
<p> <strong>PROBLEM DIAGNOSIS</strong></p>
<p>The full system, including software and hardware is available to you and accessible by you without limit during any telephone discussions with bestadvicer support personnel/tech. consultant. Any consultation related with technology/hardware/software/electronic gadgets does not include (1) problem diagnosis and support that may not be completed because of a problem with your computer or other equipment or their configuration that is beyond our control. (2) Software including the operating system and software added to the registered hardware products which are out of scope for the plan. (3) Problem that may and do result from External causes such as accident, abuse, misuse or problems with electrical power. (4) Usage that is not in accordance with product instruction provided by manufacture. (5) Failure to follow the product instruction provided by manufacture or failure to perform preventive maintenance, or problems caused by using accessories, parts, or components not compatible with the product. (6) Non-compliance with the bestadvicer tech. consultant instructions for resolving the query.  </p>
<p> <strong>MERCHANTABILITY AND FITNESS</strong></p>
<p>The directory listing is provided on an “AS-IS” basis. Bestadvicer disclaims all warranties, either express or implied, including but not limited to the implied warranties of merchantability and fitness for particular purpose. Without limiting the foregoing, bestadvicer does not warrant or represent that the Directory Listing or any part thereof is accurate or complete. You hereby assume full responsibility for all communications made by you with any consultant, professional, counsellors, or doctors, or hospital or other healthcare services providers contacted by you through the Directory Listing on bestadvicer. Further bestadvicer shall in no event be liable to you or your friend or family for any decision made or action taken by you in the reliance on information provided on the portal of bestadvicer. </p>
<p> <strong>INFRINGEMENT</strong></p>
<p>You undertake not to infringe upon or permit anyone to infringe upon any of the intellectual property rights of bestadvicer in the site, in particular the data and content posted therein, and further undertake to suitably compensate bestadvicer in this regard for the loss or damage suffered by bestadvicer due to the said infringement by you and also indemnifies bestadvicer to this effect. </p>
<p>You undertake to put bestadvicer on notice, immediately upon coming to know of any infringement of the intellectual property rights of bestadvicer, by any other user or by third parties. </p>
<p> <strong>Fair Usage Policy:</strong></p>
<p>You understand that bestadvicer does not allow an excessive number of free queries on a single issue. Only one query from a similar issue is allowed to be posted/consulted  for free at bestadvicer. And you agree that you shall follow-up by paying the fee set by the consultant for his/her answers. Also in your unlimited individual plan, you agree that you cannot post/consult for multiple queries of same issue. Also if bestadvicer detects that you use the account to post issues of another person, you plan will be cancelled. </p>
<p>Also bestadvicer reserves the right to suspend your account without any notice. And no explanation is needed by bestadvicer to be given by you. </p>
<p>Bestadvicer will not be liable for any damages of any kind arising from you of use of this site or video consulting or phone service or email communication, including, but not limited to, direct, indirect, incidental, punitive or consequential damages. </p>
<p>You have to read, acquainted yourself and understood the above-mentioned terms and conditions and that by using bestadvicer and/or Portal and the Video Consulting, Phone and Email services, You agree to the terms and conditions set forth above. </p>
<p> <strong>The following are in addition to the above ‘terms and conditons’ which bestadvicer has added on this …….. day of ………2020 for GDPR compliance and the person reading accepts the below. </strong></p>
<p>The following terminology applies applies to these Terms and Conditions, Privacy Statement and any disclaimer Notice and any or all Agreements: “Client”, “You” and “Your” refers to you, the person accessing this website and accepting the Company’s terms and conditions. “The Company”, “Ourselves”, “We” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves, or either the Client or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner, whether by formal meetings of a fixed duration or any other means, for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services/products, in accordance with and subject to prevailing Indian Law. Any use of the above terminology or other words in the singular, plural, capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same. </p>
<p> <strong>Privacy Statement:</strong></p>
<p>Bestadvicer is committed to protecting your privacy. Authorised employees within the company on a need to know basis only use any information collected from individual Clients. We constantly review our systems and data to ensure the best possible service to our Clients. There are specific offences for unauthorised actions against computer systems and data. We will investigate any such actions with a view to prosecuting and/or taking civil proceedings to recover damages against those responsible.</p>
<p> <strong>Confidentiality:</strong></p>
<p>To the extent a User or Advicer provides Confidential Information to the other, the recipient will ensure the protection of the secrecy of confidential information disclosed with the same degree of care as it uses to protect its own Confidential Information, but in no event with less than due care, and will: (a) No one shall disclose another’s Confidential Information to anyone without first obtaining the express written consent of the owner of the Confidential Information; (b) No one shall use or permit the use of another’s Confidential Information, except if it is necessary for the performance of Advisers Services (which shall include, without any limitation, the storage or transmission of Confidential Information on or through the Site for use by Adviser).</p>
<p>If and when Confidential Information is no longer needed for the performance of the  Services , at the User’s or Lawyer’s written request, the party that received Confidential Information or any other material information, will, at its expense, promptly destroy or return the disclosing party’s Confidential Information and any copies thereof contained in or on its premises, systems, or any other equipment otherwise under its control. The party that received Confidential Information agrees to provide written certification to the party disclosing the Confidential Information in compliance i.e  after the receiving the written consent.</p>
<p>Any information concerning the Client and their respective Client Records may be passed to third parties. However, Client records are regarded as confidential and therefore will not be divulged to any third party, other than our employees and if legally required to do so to the appropriate authorities. Clients have the right to request sight of, and copies of any and all Client Records we keep, on the proviso that we are given reasonable notice of such a request. Clients are requested to retain copies of any literature issued in relation to the provision of our services. Where appropriate, we shall issue Client's with appropriate written information, handouts or copies of records as part of an agreed </p>
<p>contract, for the benefit of both parties.</p>
<p> We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail. Any emails sent by this Company will only be in connection with the provision of agreed services and products.</p>
<p> <strong>Log Files:</strong></p>
<p>We use IP addresses to analyse trends, administer the site, track user's movement, and gather broad demographic information for aggregate use. IP addresses are not linked to personally identifiable information. Additionally, for systems administration, detecting usage patterns and troubleshooting purposes, our web servers automatically log standard access information including browser type, access times/open mail, URL requested, and referral URL. This information is not shared with third parties and is used only within this Company on a need-to-know basis. Any individually identifiable information related to this data will never be used in any way different to </p>
<p>that stated above without your explicit permission.</p>
<p> <strong>Cookies:</strong></p>
<p>Like most interactive web sites this Company's website uses cookies to enable us to retrieve user details for each visit. Cookies are used in some areas of our site to enable the functionality of this area and ease of use for those people visiting. Some of our affiliate partners may also use cookies.</p>
<p> <strong>Links from this website:</strong></p>
<p>We do not monitor or review the content of other party's websites which are linked to from this website. Opinions expressed or material appearing on such websites are not necessarily shared or endorsed by us and should not be regarded as the publisher of such opinions or material. Please be aware that we are not responsible for the privacy practices, or content, of these sites. We encourage our users to be aware when they leave our site & to read the privacy statements of these sites. You should evaluate the security and trustworthiness of any other site connected to this site or accessed through this site yourself, before disclosing any personal information to them. This Company will not accept any responsibility for any loss or damage in whatever manner, howsoever caused, resulting from your disclosure to third parties of personal information.</p>
<p> <strong>Copyright and Trademark:</strong></p>
<p>Copyright and other relevant intellectual property rights exists on all text relating to the Company's services and the full content of this website.
This Company's logo is a registered trademark of this Company in the India. The brand names and specific services of this Company featured on this web site are applied for trade mark as "Bestadvicer". All the content, images, graphics and videos listed or published on this website is the sole property of (Company Name) © bestadvicer - All Rights Reserved. Any form of reproduction or redistribution of all or any part of the content in the same or any different format is strictly prohibited. Any party willing to copy or use the content for their personal purpose, publishing it on a website or display publicly through any media should get exclusive permission from the site's admin. If you are looking to use the content of the site elsewhere, please contact us by emailing to bestadvicer@bestadvicer.com. The concerned team will get back to you. You may not, except with our express written permission, distribute or commercially exploit the content. Nor may you transmit it or store it in any other website or another form of 
electronic retrieval system.
</p>
<p> <strong>Force Majeure:</strong></p>
<p>Neither party shall be liable to the other for any failure to perform any obligation under any Agreement which is due to an event beyond the control of such party including but not limited to any Act of God, terrorism, war, Political insurgence, insurrection, riot, civil unrest, act of civil or military authority, uprising, earthquake, flood or any other natural or man made eventuality outside of our control, which causes the termination of an agreement or contract entered into, nor which could have been reasonably foreseen. Any Party affected by such event shall forthwith inform the other Party of the same and shall use all reasonable endeavours to comply with the terms and conditions of any Agreement contained herein.

</p>
<p> <strong>Waiver:</strong></p>
<p>Failure of either Party to insist upon strict performance of any provision of this or any Agreement or the failure of either Party to exercise any right or remedy to which it, he or they are entitled hereunder shall not constitute a waiver thereof and shall not cause a diminution of the obligations under this or any Agreement. No waiver of any of the provisions of this or any Agreement shall be effective unless it is expressly stated to be such and signed by both Parties.</p>
<p> <strong>General:</strong></p>
<p>The laws of India govern these terms and conditions. By accessing this terms or using our services/buying our products you consent to these terms and conditions and to the exclusive jurisdiction of the Indian courts in all disputes arising out of such access. If any of these terms are deemed invalid or unenforceable for any reason (including, but not limited to the exclusions and limitations set out above), then the invalid or unenforceable provision will be severed from these terms and the remaining terms will continue to apply. Failure of the Company to enforce any of the provisions set out in these Terms and Conditions and any Agreement, or failure to exercise any option to terminate, shall not be construed as waiver of such provisions and shall not affect the validity of these Terms and Conditions or of any Agreement or any part thereof, or the right thereafter to enforce each and every provision. These Terms and Conditions shall not be amended, modified, varied or supplemented except in writing and signed by duly authorised representatives of the Company.</p>
<p> <strong>Notification of Changes:</strong></p>
<p>The Company reserves the right to periodically change these conditions as it sees fit and your continued access to website or availing any of the services  will signify your acceptance of any adjustment to these terms and you are solely responsible to check the amended terms at regular intervals.  </p>

<p>If there are any changes to our privacy policy, we will announce that these changes have been made on our home page and on other key pages on our site. If there are any changes in how we use our site Clients' Personally Identifiable Information, notification by e-mail or postal mail will be made to those affected by this change. Any changes to our privacy policy will be posted on our website 30 days prior to these changes taking place. You are therefore advised to re-read this statement on a regular basis</p>
<p> <strong>CONSUMER COMPLAINT SERVICE</strong></p>
<p>We do not guarantee that your complaint will be resolved 100% as it depends on the situation of the company but we will try our level best to solve the matter to the last extent. </p>
<p> <strong>CONTACT INFORMATION</strong></p>
<p>If you have any questions or comments about these our Terms of Service as outlined above, you can contact us:</p>
<p>SUCCESSTAINMENT PRIVATE-LIMITED</p>
<p>7-KRISHNA KUNJ NR HANUMAN NA ROAD KRISHNA NAGAR MATHURA</p>
<p>Mathura UP 281001 IN</p>
<p>Email : info@bestadvicer.com</p>
<p>Tel. +91 999-788-2133</p>



</div>
<br>  <!-- // footer -->
<?php $this->load->view('include/footer'); ?>